language: php

php:
  - 5.6
  - 5.5
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer self-update
  - touch storage/testing.sqlite
  - composer install -n --prefer-dist
  - php artisan migrate --database=sqlite_testing --force
  - ./vendor/bin/codecept build
  - php artisan serve &
  - sleep 5


script:
  - ./vendor/bin/codecept run

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9a1fb8b957f92c12a6e5
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
